apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-app.fullname" . }}
  labels:
    {{- include "my-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "my-app.selectorLabels" . | nindent 4 }}
  ports:
    - name: {{ .Values.service.name | default "http" }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.name | default "http" }}
      protocol: {{ .Values.service.protocol | default "TCP" }}
